force-app/main/default/objects/TriggerHandlers__mdt/TriggerHandlers__mdt.object-meta.xml
<CustomObject>
    <label>TriggerContoller</label>
    <pluralLabel>TriggerController</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerHandlers__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Class name to be instantiated in Trigger Handler</description>
    <label>Class Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TriggerHandlers__mdt/fields/Execution_Order__c.field-meta.xml
<CustomField>
    <fullName>Execution_Order__c</fullName>
    <description>Order that trigger controller should run in Called in Ascending order.</description>
    <label>Execution Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TriggerHandlers__mdt/fields/SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Type__c</fullName>
    <description>Type of object the trigger is called on</description>
    <label>SObject Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomMetaDataTriggerHandler.cls
/**
 * Created by bjohnson on 1/27/20.
 */

public with sharing class CustomMetaDataTriggerHandler  extends TriggerHandler{

    //The run() method from TriggerHandler is overridden to execute classes found in custom metadata

    public override void run() {

         //Our first task is to identify the object on which this trigger fired.


        String firedOnsObjectType = getSObjectType();

        /*
         * This query executes against our custom metadata to return records that detail
         * what trigger handlers, and in what order, they should be called.
         */
        List<TriggerHandlers__mdt> triggerHandlersToRun = [
                SELECT Execution_Order__c, Class_Name__c
                FROM TriggerHandlers__mdt
                WHERE SObject_Type__c = :firedOnsObjectType
                ORDER BY Execution_Order__c
        ];

        for (TriggerHandlers__mdt triggerHandler: triggerHandlersToRun) {

            TriggerHandler handler;
            try{
                handler = (TriggerHandler) Type.forName(triggerHandler.Class_Name__c).newInstance();
            } catch (NullPointerException npe) {
               //TODO tell someone about this.
                System.debug('Null pointer thrown from CMDT Trigger Handler');
                continue;
            }

            // dispatch to the correct handler method
            switch on this.context {
                when BEFORE_INSERT {
                    handler.beforeInsert();
                }
                when BEFORE_UPDATE {
                    handler.beforeUpdate();
                }
                when BEFORE_DELETE {
                    handler.beforeDelete();
                }
                when AFTER_INSERT {
                    handler.afterInsert();
                }
                when AFTER_UPDATE {
                    handler.afterUpdate();
                }
                when AFTER_DELETE {
                    handler.afterDelete();
                }
                when AFTER_UNDELETE {
                    handler.afterUndelete();
                }
            }
        }
    }

    // Helper Methods
    private String getSObjectType(){
        if(Trigger.new != null){
            return Trigger.new[0].getSObjectType().getDescribe().getName();
        }else {
            return Trigger.old[0].getSObjectType().getDescribe().getName();
        }
    }
}